language: ruby
rvm:
- 2.0.0
gemfile:
- Gemfile
env:
- DB=mysql
script:
- cd matsuri2
- bundle install --standalone --clean
- RAILS_ENV=test bundle exec rake --trace db:create
- RAILS_ENV=test bundle exec rake --trace db:migrate
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
notifications:
  hipchat:
    rooms:
      secure: BL7krttYFqIoJHWkpSPDXvBuj1qr/B+lbn7hlZeOgGGPksEmhwHU5xJUm8J3nUp4atHATAxwWOL3OQ4//SeScUoC+2Op/l8TFcp8oXru1ke2MNNa0AL0LeBqxqMiIECiuOSjPEgnZZtG4AIgiTBAiJsTlJXDKnV09eixzpJTOjQ=
deploy:
  provider: heroku
  api_key:
    secure: fWJYi3EInP02ZZE2Ny3GvDU6Oj0Mulg9814w08pzHOTOJ33BKmw8R3GH0RFV28Vs30n8LWZJ2z6tQrlT00xj2OTgdP2dt8RefOCXXrPQK9YiaeHENg0d+H/aDQUGZylFBEIcainPeROxeKkp0mkxVVZUsQSh+9MiM22ncidT4Dk=
  app:
    master: matsuri2
  on:
    repo: doyomeki/matsuri2
