language: ruby
rvm:
- 2.0.0
script:
- cd matsuri2
- bundle install --standalone --clean
- bundle exec rake test
notifications:
  hipchat:
    rooms:
      secure: BL7krttYFqIoJHWkpSPDXvBuj1qr/B+lbn7hlZeOgGGPksEmhwHU5xJUm8J3nUp4atHATAxwWOL3OQ4//SeScUoC+2Op/l8TFcp8oXru1ke2MNNa0AL0LeBqxqMiIECiuOSjPEgnZZtG4AIgiTBAiJsTlJXDKnV09eixzpJTOjQ=
