notifications:
  hipchat:
    rooms:
      secure: BL7krttYFqIoJHWkpSPDXvBuj1qr/B+lbn7hlZeOgGGPksEmhwHU5xJUm8J3nUp4atHATAxwWOL3OQ4//SeScUoC+2Op/l8TFcp8oXru1ke2MNNa0AL0LeBqxqMiIECiuOSjPEgnZZtG4AIgiTBAiJsTlJXDKnV09eixzpJTOjQ=
